name: 🎨 Windows
on: 
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'gd3'
  workflow_dispatch:

env:
  GOOST_BASE_BRANCH: gd3
  SCONSFLAGS: godot_modules_enabled=no verbose=yes warnings=all werror=yes debug_symbols=no --jobs=4
  SCONS_CACHE_MSVC_CONFIG: true
  SCONS_CACHE_LIMIT: 8192

jobs:
  windows-editor:
    runs-on: "windows-latest"
    name: Editor (target=release_debug, tools=yes)
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # Editing this is pretty dangerous for Windows since it can break.
    # Needs to be properly tested with a fresh cache.
    - name: Load .scons_cache directory
      id: windows-editor-cache
      uses: RevoluPowered/cache@v2.1
      with:
        path: /.scons_cache/
        key: ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}
          ${{github.job}}-${{env.GOOST_BASE_BRANCH}}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version

    - name: Compilation
      env:
        SCONS_CACHE: /.scons_cache/
      run: |
        scons platform=windows tools=yes target=release_debug

    - uses: actions/upload-artifact@v2
      with:
        name: godot.windows.opt.tools.64.goost
        path: godot/bin/godot.windows.opt.tools.64.goost.exe

  windows-template:
    runs-on: "windows-latest"
    name: Template (target=release, tools=no)

    steps:
    - uses: actions/checkout@v2

    # Editing this is pretty dangerous for Windows since it can break.
    # Needs to be properly tested with a fresh cache.
    - name: Load .scons_cache directory
      id: windows-template-cache
      uses: RevoluPowered/cache@v2.1
      with:
        path: /.scons_cache/
        key: ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{github.job}}-${{env.GOOST_BASE_BRANCH}}-${{github.ref}}
          ${{github.job}}-${{env.GOOST_BASE_BRANCH}}

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Configuring Python packages
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons pywin32
        python --version
        scons --version

    - name: Compilation
      env:
        SCONS_CACHE: /.scons_cache/
      run: |
        scons platform=windows target=release tools=no
